#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# 2011 Nico Schottelius (nico-kbsd at schottelius.org)
#
# This file is part of kbsd.
#
# kbsd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# kbsd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kbsd. If not, see <http://www.gnu.org/licenses/>.
#
#

import os
import re
import time

BASE="/sys/bus/platform/drivers/applesmc/applesmc.768"
LIGHT_SENSOR="light"
LED="smc::kbd_backlight/brightness"

BRIGHT_MAX = 255

light_path = os.path.join(BASE, LIGHT_SENSOR)
led_path = os.path.join(BASE, LED)

light_match = r'^\(\\\(.*\\\),'
light_replace = r'\1'

while True:
    light_fd = open(light_path, "r")
    light_raw = open(light_path, "r").readlines()
    light = light_raw[0].rstrip('\n')
    light = light.strip('(')

    #light_value = re.sub(light_match, light_replace, light)

    print(light)

    time.sleep(1)

    
